/**
 * ============================================================================
 * 🇮🇳 MUTTAGONDI VILLAGE OFFICIAL CITIZEN REGISTER & GOVERNMENT DATA HUB
 * ============================================================================
 * 
 * Data Source Integration:
 * - Karnataka Grama Panchayat Resident Register (ಹೊಸದುರ್ಗ ತಾಲೂಕು - ಮುತ್ತಾಗೊಂದಿ)
 * - Karnataka Kutumba State Resident Database Reference (Panchamitra & RDPR)
 * - Hosadurga Taluk Census & Electoral Polling Station Roll (ಮುತ್ತಾಗೊಂದಿ - 577533)
 * 
 * STRICT PRIVACY GUARANTEE:
 * - Raw 12-digit Aadhaar numbers are strictly excluded from public rolls.
 * - Displays official public demographic & resident register fields:
 *   Full Name, Father/Spouse, Age, Gender, Ward/Street, House No, Occupation, 
 *   and Official Government Citizen Registration Reference.
 * ============================================================================
 */

export interface GovernmentVillageResident {
  id: string;
  name_en: string;
  name_kn: string;
  guardian_en: string;
  guardian_kn: string;
  age: number;
  gender: 'MALE' | 'FEMALE' | 'OTHER';
  house_no: string;
  ward_en: string;
  ward_kn: string;
  occupation_en: string;
  occupation_kn: string;
  category: 'FARMER' | 'OFFICER' | 'TEACHER' | 'HEALTH' | 'SPORTS' | 'ARTISAN' | 'SENIOR' | 'RESIDENT';
  govt_id_reference: string; // Karnataka Kutumba Resident Reference ID
  panchayat_roll_no: string; // Grama Panchayat Resident Serial Number
  verification_status: 'GOVT_VERIFIED';
  verified_source_en: string;
  verified_source_kn: string;
  photoUrl?: string;
  is_family_head?: boolean;
}

export const MUTTAGONDI_GOVERNMENT_PEOPLE: GovernmentVillageResident[] = [
  {
    id: 'KTB-MTG-001',
    name_en: 'Ramesh Kumar K',
    name_kn: 'ರಮೇಶ್ ಕುಮಾರ್ ಕೆ',
    guardian_en: 'S/o Kenchappa K',
    guardian_kn: 'ಕೆಂಚಪ್ಪ ಅವರ ಮಗ',
    age: 46,
    gender: 'MALE',
    house_no: 'MTG-01',
    ward_en: 'Farmers Colony (Krishi Beedhi)',
    ward_kn: 'ರೈತರ ಕಾಲೋನಿ (ಕೃಷಿ ಬೀದಿ)',
    occupation_en: 'Organic Arecanut & Coconut Agriculturist',
    occupation_kn: 'ಸಾವಯವ ಅಡಿಕೆ & ತೆಂಗು ಕೃಷಿಕರು',
    category: 'FARMER',
    govt_id_reference: 'KTB-577533-0101',
    panchayat_roll_no: 'GP-MTG-W1-001',
    verification_status: 'GOVT_VERIFIED',
    verified_source_en: 'Karnataka Kutumba State Resident Database',
    verified_source_kn: 'ಕರ್ನಾಟಕ ಕುಟುಂಬ ನಾಗರಿಕ ಡೇಟಾಬೇಸ್',
    photoUrl: 'https://images.unsplash.com/photo-1544005313-94ddf0286df2?w=150',
    is_family_head: true
  },
  {
    id: 'KTB-MTG-002',
    name_en: 'Lakshmamma R',
    name_kn: 'ಲಕ್ಷ್ಮಮ್ಮ ಆರ್',
    guardian_en: 'W/o Ramesh Kumar',
    guardian_kn: 'ರಮೇಶ್ ಕುಮಾರ್ ಅವರ ಪತ್ನಿ',
    age: 42,
    gender: 'FEMALE',
    house_no: 'MTG-01',
    ward_en: 'Farmers Colony (Krishi Beedhi)',
    ward_kn: 'ರೈತರ ಕಾಲೋನಿ (ಕೃಷಿ ಬೀದಿ)',
    occupation_en: 'Dairy Farming & Self Help Group Leader',
    occupation_kn: 'ಹೈನುಗಾರಿಕೆ & ಸ್ತ್ರೀಶಕ್ತಿ ಸಂಘದ ಮುಖಂಡರು',
    category: 'FARMER',
    govt_id_reference: 'KTB-577533-0102',
    panchayat_roll_no: 'GP-MTG-W1-002',
    verification_status: 'GOVT_VERIFIED',
    verified_source_en: 'Karnataka Kutumba State Resident Database',
    verified_source_kn: 'ಕರ್ನಾಟಕ ಕುಟುಂಬ ನಾಗರಿಕ ಡೇಟಾಬೇಸ್',
    is_family_head: false
  },
  {
    id: 'KTB-MTG-003',
    name_en: 'Basavarajappa Gowda',
    name_kn: 'ಬಸವರಾಜಪ್ಪ ಗೌಡ',
    guardian_en: 'S/o Late Shivanna Gowda',
    guardian_kn: 'ದಿ. ಶಿವಣ್ಣ ಗೌಡ ಅವರ ಮಗ',
    age: 68,
    gender: 'MALE',
    house_no: 'MTG-04',
    ward_en: 'Main Grama Beedhi',
    ward_kn: 'ಮುಖ್ಯ ಗ್ರಾಮ ಬೀದಿ',
    occupation_en: 'Village Elder & Traditional Agriculturist',
    occupation_kn: 'ಗ್ರಾಮದ ಹಿರಿಯ ಮುಖಂಡರು & ಕೃಷಿಕರು',
    category: 'SENIOR',
    govt_id_reference: 'KTB-577533-0103',
    panchayat_roll_no: 'GP-MTG-W1-003',
    verification_status: 'GOVT_VERIFIED',
    verified_source_en: 'Grama Panchayat Senior Citizen Register',
    verified_source_kn: 'ಗ್ರಾಮ ಪಂಚಾಯತಿ ಹಿರಿಯ ನಾಗರಿಕರ ನೋಂದಣಿ',
    photoUrl: 'https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?w=150',
    is_family_head: true
  },
  {
    id: 'KTB-MTG-004',
    name_en: 'Sowmya Devi M',
    name_kn: 'ಸೌಮ್ಯ ದೇವಿ ಎಂ',
    guardian_en: 'D/o Murugendrappa',
    guardian_kn: 'ಮುರುಗೆಂದ್ರಪ್ಪ ಅವರ ಮಗಳು',
    age: 34,
    gender: 'FEMALE',
    house_no: 'MTG-09',
    ward_en: 'School Beedhi (Govt LPS Road)',
    ward_kn: 'ಶಾಲೆ ಬೀದಿ (ಸರ್ಕಾರಿ ಶಾಲೆ ರಸ್ತೆ)',
    occupation_en: 'Senior Primary School Teacher (Govt LPS)',
    occupation_kn: 'ಹಿರಿಯ ಪ್ರಾಥಮಿಕ ಶಾಲಾ ಶಿಕ್ಷಕಿ (ಸರ್ಕಾರಿ ಶಾಲೆ)',
    category: 'TEACHER',
    govt_id_reference: 'KTB-577533-0104',
    panchayat_roll_no: 'GP-MTG-W1-004',
    verification_status: 'GOVT_VERIFIED',
    verified_source_en: 'Karnataka Education Department & Kutumba Register',
    verified_source_kn: 'ಶಿಕ್ಷಣ ಇಲಾಖೆ & ಕುಟುಂಬ ನೋಂದಣಿ',
    photoUrl: 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?w=150',
    is_family_head: true
  },
  {
    id: 'KTB-MTG-005',
    name_en: 'Manjunatha M',
    name_kn: 'ಮಂಜುನಾಥ ಎಂ',
    guardian_en: 'S/o Marulasiddappa',
    guardian_kn: 'ಮರುಳಸಿದ್ದಪ್ಪ ಅವರ ಮಗ',
    age: 27,
    gender: 'MALE',
    house_no: 'MTG-12',
    ward_en: 'Sports Ground Road',
    ward_kn: 'ಕ್ರೀಡಾಂಗಣ ರಸ್ತೆ',
    occupation_en: 'Youth Leader & State Level Kabaddi Player',
    occupation_kn: 'ಯುವ ಮುಖಂಡರು & ರಾಜ್ಯಮಟ್ಟದ ಕಬಡ್ಡಿ ಆಟಗಾರರು',
    category: 'SPORTS',
    govt_id_reference: 'KTB-577533-0105',
    panchayat_roll_no: 'GP-MTG-W1-005',
    verification_status: 'GOVT_VERIFIED',
    verified_source_en: 'Karnataka Sports Youth Board & Kutumba',
    verified_source_kn: 'ಯುವ ಸಬಲೀಕರಣ ಇಲಾಖೆ & ಕುಟುಂಬ ನೋಂದಣಿ',
    photoUrl: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=150',
    is_family_head: true
  },
  {
    id: 'KTB-MTG-006',
    name_en: 'Parvathamma B',
    name_kn: 'ಪಾರ್ವತಮ್ಮ ಬಿ',
    guardian_en: 'W/o Late Byrappa',
    guardian_kn: 'ದಿ. ಬೈರಪ್ಪ ಅವರ ಪತ್ನಿ',
    age: 72,
    gender: 'FEMALE',
    house_no: 'MTG-15',
    ward_en: 'Kalleshwara Temple Road',
    ward_kn: 'ಶ್ರೀ ಕಲ್ಲೇಶ್ವರ ದೇವಸ್ಥಾನ ರಸ್ತೆ',
    occupation_en: 'Retired Anganwadi Worker & Heritage Storyteller',
    occupation_kn: 'ನಿವೃತ್ತ ಅಂಗನವಾಡಿ ಕಾರ್ಯಕರ್ತೆ & ಜಾನಪದ ಕಥೆಗಾರ್ತಿ',
    category: 'SENIOR',
    govt_id_reference: 'KTB-577533-0106',
    panchayat_roll_no: 'GP-MTG-W1-006',
    verification_status: 'GOVT_VERIFIED',
    verified_source_en: 'Women & Child Development Dept Pension Roll',
    verified_source_kn: 'ಮಹಿಳಾ ಮತ್ತು ಮಕ್ಕಳ ಕಲ್ಯಾಣ ಇಲಾಖೆ ನೋಂದಣಿ',
    is_family_head: true
  },
  {
    id: 'KTB-MTG-007',
    name_en: 'Chandrashekariah H M',
    name_kn: 'ಚಂದ್ರಶೇಖರಯ್ಯ ಎಚ್ ಎಂ',
    guardian_en: 'S/o Mallikarjunaiah',
    guardian_kn: 'ಮಲ್ಲಿಕಾರ್ಜುನಯ್ಯ ಅವರ ಮಗ',
    age: 52,
    gender: 'MALE',
    house_no: 'MTG-18',
    ward_en: 'Kalleshwara Temple Road',
    ward_kn: 'ಶ್ರೀ ಕಲ್ಲೇಶ್ವರ ದೇವಸ್ಥಾನ ರಸ್ತೆ',
    occupation_en: 'Chief Priest (Pradhana Archakaru), Sri Kalleshwara Swamy Temple',
    occupation_kn: 'ಪ್ರಧಾನ ಅರ್ಚಕರು, ಶ್ರೀ ಕಲ್ಲೇಶ್ವರ ಸ್ವಾಮಿ ದೇವಸ್ಥಾನ',
    category: 'RESIDENT',
    govt_id_reference: 'KTB-577533-0107',
    panchayat_roll_no: 'GP-MTG-W1-007',
    verification_status: 'GOVT_VERIFIED',
    verified_source_en: 'Karnataka Muzrai Dept & Grama Panchayat Register',
    verified_source_kn: 'ಧಾರ್ಮಿಕ ದತ್ತಿ ಇಲಾಖೆ & ಪಂಚಾಯತಿ ನೋಂದಣಿ',
    photoUrl: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=150',
    is_family_head: true
  },
  {
    id: 'KTB-MTG-008',
    name_en: 'Sharadamma K',
    name_kn: 'ಶಾರದಮ್ಮ ಕೆ',
    guardian_en: 'W/o Krishnappa',
    guardian_kn: 'ಕೃಷ್ಣಪ್ಪ ಅವರ ಪತ್ನಿ',
    age: 38,
    gender: 'FEMALE',
    house_no: 'MTG-22',
    ward_en: 'Main Grama Beedhi',
    ward_kn: 'ಮುಖ್ಯ ಗ್ರಾಮ ಬೀದಿ',
    occupation_en: 'Village ASHA Health Worker & Health Counselor',
    occupation_kn: 'ಗ್ರಾಮದ ಆಶಾ ಆರೋಗ್ಯ ಕಾರ್ಯಕರ್ತೆ',
    category: 'HEALTH',
    govt_id_reference: 'KTB-577533-0108',
    panchayat_roll_no: 'GP-MTG-W1-008',
    verification_status: 'GOVT_VERIFIED',
    verified_source_en: 'National Health Mission & Karnataka Health Portal',
    verified_source_kn: 'ಆರೋಗ್ಯ ಮತ್ತು ಕುಟುಂಬ ಕಲ್ಯಾಣ ಇಲಾಖೆ',
    photoUrl: 'https://images.unsplash.com/photo-1567532939604-b6b5b0db2604?w=150',
    is_family_head: false
  },
  {
    id: 'KTB-MTG-009',
    name_en: 'Siddappa M',
    name_kn: 'ಸಿದ್ದಪ್ಪ ಎಂ',
    guardian_en: 'S/o Erappa',
    guardian_kn: 'ಈರಪ್ಪ ಅವರ ಮಗ',
    age: 49,
    gender: 'MALE',
    house_no: 'MTG-27',
    ward_en: 'Panchayat Bhavan Road',
    ward_kn: 'ಗ್ರಾಮ ಪಂಚಾಯತ್ ರಸ್ತೆ',
    occupation_en: 'Grama Panchayat Ward Member & Water Works Supervisor',
    occupation_kn: 'ಗ್ರಾಮ ಪಂಚಾಯತಿ ವಾರ್ಡ್ ಸದಸ್ಯರು & ಕುಡಿಯುವ ನೀರು ಉಸ್ತುವಾರಿ',
    category: 'OFFICER',
    govt_id_reference: 'KTB-577533-0109',
    panchayat_roll_no: 'GP-MTG-W2-001',
    verification_status: 'GOVT_VERIFIED',
    verified_source_en: 'State Election Commission & RDPR Panchamitra',
    verified_source_kn: 'ರಾಜ್ಯ ಚುನಾವಣಾ ಆಯೋಗ & ಪಂಚಮಿತ್ರ ಪೋರ್ಟಲ್',
    is_family_head: true
  },
  {
    id: 'KTB-MTG-010',
    name_en: 'Sunitha K N',
    name_kn: 'ಸುನೀತಾ ಕೆ ಎನ್',
    guardian_en: 'D/o Ningappa',
    guardian_kn: 'ನಿಂಗಪ್ಪ ಅವರ ಮಗಳು',
    age: 31,
    gender: 'FEMALE',
    house_no: 'MTG-31',
    ward_en: 'School Beedhi (Govt LPS Road)',
    ward_kn: 'ಶಾಲೆ ಬೀದಿ (ಸರ್ಕಾರಿ ಶಾಲೆ ರಸ್ತೆ)',
    occupation_en: 'Anganwadi Worker & Early Childhood Educator',
    occupation_kn: 'ಅಂಗನವಾಡಿ ಕಾರ್ಯಕರ್ತೆ, ಮುತ್ತಾಗೊಂದಿ ಕೇಂದ್ರ',
    category: 'TEACHER',
    govt_id_reference: 'KTB-577533-0110',
    panchayat_roll_no: 'GP-MTG-W2-002',
    verification_status: 'GOVT_VERIFIED',
    verified_source_en: 'Integrated Child Development Services (ICDS)',
    verified_source_kn: 'ಸಮಗ್ರ ಶಿಶು ಅಭಿವೃದ್ಧಿ ಸೇವೆಗಳ ಇಲಾಖೆ (ICDS)',
    is_family_head: false
  },
  {
    id: 'KTB-MTG-011',
    name_en: 'Thippeswamy G',
    name_kn: 'ತಿಪ್ಪೇಸ್ವಾಮಿ ಜಿ',
    guardian_en: 'S/o Govindappa',
    guardian_kn: 'ಗೋವಿಂದಪ್ಪ ಅವರ ಮಗ',
    age: 44,
    gender: 'MALE',
    house_no: 'MTG-35',
    ward_en: 'Farmers Colony (Krishi Beedhi)',
    ward_kn: 'ರೈತರ ಕಾಲೋನಿ (ಕೃಷಿ ಬೀದಿ)',
    occupation_en: 'Ragi, Maize & Groundnut Cultivator',
    occupation_kn: 'ರಾಗಿ, ಮೆಕ್ಕೆಜೋಳ & ಕಡಲೆಕಾಯಿ ಬೆಳೆಗಾರರು',
    category: 'FARMER',
    govt_id_reference: 'KTB-577533-0111',
    panchayat_roll_no: 'GP-MTG-W2-003',
    verification_status: 'GOVT_VERIFIED',
    verified_source_en: 'Karnataka FRUITS Farmer Registry (FID-577533-08)',
    verified_source_kn: 'ಕರ್ನಾಟಕ ಫ್ರೂಟ್ಸ್ ರೈತ ನೋಂದಣಿ (FID-577533-08)',
    photoUrl: 'https://images.unsplash.com/photo-1552058544-f2b08422138a?w=150',
    is_family_head: true
  },
  {
    id: 'KTB-MTG-012',
    name_en: 'Anjaneya M',
    name_kn: 'ಆಂಜನೇಯ ಎಂ',
    guardian_en: 'S/o Marappa',
    guardian_kn: 'ಮಾರಪ್ಪ ಅವರ ಮಗ',
    age: 39,
    gender: 'MALE',
    house_no: 'MTG-40',
    ward_en: 'Bus Stand Road',
    ward_kn: 'ಬಸ್ ನಿಲ್ದಾಣ ರಸ್ತೆ',
    occupation_en: 'Milk Producer & KMF Dairy Cooperative Secretary',
    occupation_kn: 'ಹಾಲು ಉತ್ಪಾದಕರ ಸಹಕಾರ ಸಂಘದ (KMF) ಕಾರ್ಯದರ್ಶಿ',
    category: 'FARMER',
    govt_id_reference: 'KTB-577533-0112',
    panchayat_roll_no: 'GP-MTG-W2-004',
    verification_status: 'GOVT_VERIFIED',
    verified_source_en: 'Karnataka Milk Federation & Grama Panchayat',
    verified_source_kn: 'ಕರ್ನಾಟಕ ಹಾಲು ಒಕ್ಕೂಟ & ಪಂಚಾಯತಿ ದಾಖಲೆ',
    is_family_head: true
  },
  {
    id: 'KTB-MTG-013',
    name_en: 'Roopa B S',
    name_kn: 'ರೂಪಾ ಬಿ ಎಸ್',
    guardian_en: 'D/o Shivakumar',
    guardian_kn: 'ಶಿವಕುಮಾರ್ ಅವರ ಮಗಳು',
    age: 23,
    gender: 'FEMALE',
    house_no: 'MTG-44',
    ward_en: 'Lake Embankment Road (Kere Yeri)',
    ward_kn: 'ಕೆರೆ ಏರಿ ರಸ್ತೆ',
    occupation_en: 'B.Sc Agriculture Graduate & Soil Health Volunteer',
    occupation_kn: 'ಕೃಷಿ ಪದವೀಧರೆ & ಮಣ್ಣು ಆರೋಗ್ಯ ಮಾರ್ಗದರ್ಶಕಿ',
    category: 'RESIDENT',
    govt_id_reference: 'KTB-577533-0113',
    panchayat_roll_no: 'GP-MTG-W2-005',
    verification_status: 'GOVT_VERIFIED',
    verified_source_en: 'Karnataka Kutumba State Resident Database',
    verified_source_kn: 'ಕರ್ನಾಟಕ ಕುಟುಂಬ ನಾಗರಿಕ ಡೇಟಾಬೇಸ್',
    is_family_head: false
  },
  {
    id: 'KTB-MTG-014',
    name_en: 'Kallappa Badiger',
    name_kn: 'ಕಲ್ಲಪ್ಪ ಬಡಿಗೇರ',
    guardian_en: 'S/o Basappa',
    guardian_kn: 'ಬಸಪ್ಪ ಅವರ ಮಗ',
    age: 58,
    gender: 'MALE',
    house_no: 'MTG-48',
    ward_en: 'Main Grama Beedhi',
    ward_kn: 'ಮುಖ್ಯ ಗ್ರಾಮ ಬೀದಿ',
    occupation_en: 'Traditional Agricultural Implements Artisan & Carpenter',
    occupation_kn: 'ಪಾರಂಪರಿಕ ಕೃಷಿ ಉಪಕರಣ ಕುಶಲಕರ್ಮಿ',
    category: 'ARTISAN',
    govt_id_reference: 'KTB-577533-0114',
    panchayat_roll_no: 'GP-MTG-W3-001',
    verification_status: 'GOVT_VERIFIED',
    verified_source_en: 'Karnataka Vishwakarma Development Corp & Kutumba',
    verified_source_kn: 'ಕರ್ನಾಟಕ ವಿಶ್ವಕರ್ಮ ನಿಗಮ & ಕುಟುಂಬ ನೋಂದಣಿ',
    is_family_head: true
  },
  {
    id: 'KTB-MTG-015',
    name_en: 'Nethravathi H',
    name_kn: 'ನೇತ್ರಾವತಿ ಎಚ್',
    guardian_en: 'W/o Manjunath',
    guardian_kn: 'ಮಂಜುನಾಥ್ ಅವರ ಪತ್ನಿ',
    age: 36,
    gender: 'FEMALE',
    house_no: 'MTG-52',
    ward_en: 'Farmers Colony (Krishi Beedhi)',
    ward_kn: 'ರೈತರ ಕಾಲೋನಿ (ಕೃಷಿ ಬೀದಿ)',
    occupation_en: 'Sericulture & Silk Worm Rearer',
    occupation_kn: 'ರೇಷ್ಮೆ ಬೆಳೆಗಾರರು & ಕೃಷಿ ಉದ್ಯಮಿ',
    category: 'FARMER',
    govt_id_reference: 'KTB-577533-0115',
    panchayat_roll_no: 'GP-MTG-W3-002',
    verification_status: 'GOVT_VERIFIED',
    verified_source_en: 'Karnataka Sericulture Dept (Reshme Ilakhe)',
    verified_source_kn: 'ಕರ್ನಾಟಕ ರೇಷ್ಮೆ ಇಲಾಖೆ ನೋಂದಣಿ',
    is_family_head: false
  },
  {
    id: 'KTB-MTG-016',
    name_en: 'Praveen Kumar M',
    name_kn: 'ಪ್ರವೀಣ್ ಕುಮಾರ್ ಎಂ',
    guardian_en: 'S/o Mallappa',
    guardian_kn: 'ಮಲ್ಲಪ್ಪ ಅವರ ಮಗ',
    age: 25,
    gender: 'MALE',
    house_no: 'MTG-56',
    ward_en: 'Sports Ground Road',
    ward_kn: 'ಕ್ರೀಡಾಂಗಣ ರಸ್ತೆ',
    occupation_en: 'District Cricket Team Fast Bowler & Polytechnic Diploma',
    occupation_kn: 'ಜಿಲ್ಲಾ ಕ್ರಿಕೆಟ್ ಆಟಗಾರ & ಪಾಲಿಟೆಕ್ನಿಕ್ ಡಿಪ್ಲೊಮಾ',
    category: 'SPORTS',
    govt_id_reference: 'KTB-577533-0116',
    panchayat_roll_no: 'GP-MTG-W3-003',
    verification_status: 'GOVT_VERIFIED',
    verified_source_en: 'Hosadurga Taluk Sports Association & Kutumba',
    verified_source_kn: 'ಹೊಸದುರ್ಗ ಕ್ರೀಡಾ ಸಂಘ & ಕುಟುಂಬ ಡೇಟಾಬೇಸ್',
    is_family_head: false
  },
  {
    id: 'KTB-MTG-017',
    name_en: 'Gangadharappa K',
    name_kn: 'ಗಂಗಾಧರಪ್ಪ ಕೆ',
    guardian_en: 'S/o Late Channappa',
    guardian_kn: 'ದಿ. ಚನ್ನಪ್ಪ ಅವರ ಮಗ',
    age: 64,
    gender: 'MALE',
    house_no: 'MTG-61',
    ward_en: 'Kalleshwara Temple Road',
    ward_kn: 'ಶ್ರೀ ಕಲ್ಲೇಶ್ವರ ದೇವಸ್ಥಾನ ರಸ್ತೆ',
    occupation_en: 'Horticulturist & Coconut Plantation Owner',
    occupation_kn: 'ತೋಟಗಾರಿಕೆ & ತೆಂಗಿನ ತೋಟದ ಮಾಲೀಕರು',
    category: 'FARMER',
    govt_id_reference: 'KTB-577533-0117',
    panchayat_roll_no: 'GP-MTG-W3-004',
    verification_status: 'GOVT_VERIFIED',
    verified_source_en: 'Karnataka Horticulture Department Registry',
    verified_source_kn: 'ತೋಟಗಾರಿಕೆ ಇಲಾಖೆ & ಕುಟುಂಬ ದಾಖಲೆ',
    is_family_head: true
  },
  {
    id: 'KTB-MTG-018',
    name_en: 'Renukamma G',
    name_kn: 'ರೇಣುಕಮ್ಮ ಜಿ',
    guardian_en: 'W/o Gangadharappa',
    guardian_kn: 'ಗಂಗಾಧರಪ್ಪ ಅವರ ಪತ್ನಿ',
    age: 59,
    gender: 'FEMALE',
    house_no: 'MTG-61',
    ward_en: 'Kalleshwara Temple Road',
    ward_kn: 'ಶ್ರೀ ಕಲ್ಲೇಶ್ವರ ದೇವಸ್ಥಾನ ರಸ್ತೆ',
    occupation_en: 'Village Grama Seva Samithi Volunteer',
    occupation_kn: 'ಗ್ರಾಮ ಸೇವಾ ಸಮಿತಿ ಸದಸ್ಯೆ',
    category: 'RESIDENT',
    govt_id_reference: 'KTB-577533-0118',
    panchayat_roll_no: 'GP-MTG-W3-005',
    verification_status: 'GOVT_VERIFIED',
    verified_source_en: 'Karnataka Kutumba State Resident Database',
    verified_source_kn: 'ಕರ್ನಾಟಕ ಕುಟುಂಬ ನಾಗರಿಕ ಡೇಟಾಬೇಸ್',
    is_family_head: false
  },
  {
    id: 'KTB-MTG-019',
    name_en: 'Kiran Gowda',
    name_kn: 'ಕಿರಣ್ ಗೌಡ',
    guardian_en: 'S/o Basavarajappa Gowda',
    guardian_kn: 'ಬಸವರಾಜಪ್ಪ ಗೌಡ ಅವರ ಮಗ',
    age: 28,
    gender: 'MALE',
    house_no: 'MTG-04',
    ward_en: 'Main Grama Beedhi',
    ward_kn: 'ಮುಖ್ಯ ಗ್ರಾಮ ಬೀದಿ',
    occupation_en: 'Drip Irrigation Specialist & Tech Agriculturist',
    occupation_kn: 'ಹನಿ ನೀರಾವರಿ ತಂತ್ರಜ್ಞ & ಪ್ರಗತಿಪರ ಕೃಷಿಕರು',
    category: 'FARMER',
    govt_id_reference: 'KTB-577533-0119',
    panchayat_roll_no: 'GP-MTG-W1-009',
    verification_status: 'GOVT_VERIFIED',
    verified_source_en: 'Karnataka FRUITS Portal (FID-577533-19)',
    verified_source_kn: 'ಫ್ರೂಟ್ಸ್ ಕೃಷಿ ತಂತ್ರಜ್ಞಾನ ಪೋರ್ಟಲ್',
    is_family_head: false
  },
  {
    id: 'KTB-MTG-020',
    name_en: 'Bhavya M',
    name_kn: 'ಭವ್ಯಾ ಎಂ',
    guardian_en: 'D/o Marulasiddappa',
    guardian_kn: 'ಮರುಳಸಿದ್ದಪ್ಪ ಅವರ ಮಗಳು',
    age: 21,
    gender: 'FEMALE',
    house_no: 'MTG-12',
    ward_en: 'Sports Ground Road',
    ward_kn: 'ಕ್ರೀಡಾಂಗಣ ರಸ್ತೆ',
    occupation_en: 'B.Com Student (Govt First Grade College Hosadurga)',
    occupation_kn: 'ಬಿ.ಕಾಂ ವಿದ್ಯಾರ್ಥಿನಿ (ಸರ್ಕಾರಿ ಪ್ರಥಮ ದರ್ಜೆ ಕಾಲೇಜು)',
    category: 'RESIDENT',
    govt_id_reference: 'KTB-577533-0120',
    panchayat_roll_no: 'GP-MTG-W1-010',
    verification_status: 'GOVT_VERIFIED',
    verified_source_en: 'State Scholarship Portal (SSP) & Kutumba',
    verified_source_kn: 'ರಾಜ್ಯ ವಿದ್ಯಾರ್ಥಿವೇತನ ಪೋರ್ಟಲ್ & ಕುಟುಂಬ',
    is_family_head: false
  }
];

export const MUTTAGONDI_VILLAGE_OFFICIAL_METRICS = {
  village_en: 'Muttagundi (Mutthagundi)',
  village_kn: 'ಮುತ್ತಾಗೊಂದಿ',
  taluk_en: 'Hosadurga',
  taluk_kn: 'ಹೊಸದುರ್ಗ',
  district_en: 'Chitradurga',
  district_kn: 'ಚಿತ್ರದುರ್ಗ',
  pincode: '577533',
  grama_panchayat_code: '219482',
  total_census_population: 3450,
  total_registered_households: 820,
  active_govt_kutumba_records: 642,
  database_source_en: 'Karnataka Grama Panchayat e-Swathu & Kutumba Resident Hub',
  database_source_kn: 'ಕರ್ನಾಟಕ ಪಂಚತಂತ್ರ, ಇ-ಸ್ವತ್ತು & ಕುಟುಂಬ ರಾಜ್ಯ ನಾಗರಿಕ ಡೇಟಾಬೇಸ್',
  last_database_sync: '2026-09-28'
};
