import {
  NewsItem,
  EventItem,
  Tournament,
  CropItem,
  TempleItem,
  HistoryItem,
  StoryItem,
  VillageStats,
  AchievementItem,
  GalleryItem,
  SocialLink,
  EmergencyAlert,
  UserProfile,
  Conversation,
  ChatMessage,
  CommitteeMember,
  CommitteeContribution,
  CommitteeLoan,
  CommitteeExpense,
  CommitteeTransaction,
  CommitteeAuditLog
} from '../types';

export const isSuperAdminEmail = (email?: string | null, name?: string | null): boolean => {
  const e = (email || '').toLowerCase().trim();
  const n = (name || '').toLowerCase().trim();

  // If an email exists, it MUST be one of the authorized admin emails
  if (e) {
    return (
      e === 'vvini4803@gmail.com' ||
      e === 'vvini@gmail.com' ||
      e === 'admin@muttagundi.org'
    );
  }

  // Fallback only for internal seed admin without an email
  return n === 'vvini4803' || n === 'vvini';
};

// Clean Default Users (Village Admin & Moderator for initial login)
export const SEED_USERS: UserProfile[] = [
  {
    uid: 'admin_vvini4803',
    name: 'vvini4803',
    name_kn: 'ವಿನಯ್ (ಮುಖ್ಯ ಸೂಪರ್ ಅಡ್ಮಿನ್)',
    phone: '+91 7483254968',
    email: 'vvini4803@gmail.com',
    role: 'SUPER_ADMIN',
    language: 'kn',
    photoUrl: 'https://api.dicebear.com/7.x/bottts/svg?seed=vvini4803',
    bio: 'Lead Developer & Super Administrator of Muttagundi Village Portal',
    bio_kn: 'ಮುಖ್ಯ ತಂತ್ರಾಂಶ ಅಭಿವೃದ್ಧಿಕಾರರು & ಸೂಪರ್ ಅಡ್ಮಿನ್',
    account_status: 'ACTIVE',
    created_at: new Date().toISOString(),
    last_login: new Date().toISOString(),
    is_phone_verified: true,
    community_category: 'PROFESSIONAL',
    allow_find_me: true,
    privacy_find: 'EVERYONE',
    privacy_message: 'EVERYONE'
  },
  {
    uid: 'admin_101',
    name: 'Muttagundi Admin',
    name_kn: 'ಮುತ್ತಾಗೊಂದಿ ಆಡಳಿತಾಧಿಕಾರಿ',
    phone: '+91 7483254968',
    email: 'admin@muttagundi.org',
    role: 'SUPER_ADMIN',
    language: 'kn',
    photoUrl: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=150',
    bio: 'Grama Panchayat Official & Village Administrator',
    bio_kn: 'ಗ್ರಾಮ ಪಂಚಾಯತಿ ಅಧಿಕೃತ ನಿರ್ವಾಹಕರು',
    account_status: 'ACTIVE',
    created_at: new Date().toISOString(),
    last_login: new Date().toISOString(),
    is_phone_verified: true,
    community_category: 'PROFESSIONAL',
    allow_find_me: true,
    privacy_find: 'EVERYONE',
    privacy_message: 'EVERYONE'
  },
  {
    uid: 'usr_ramesh_farmer',
    name: 'Ramesh Kumar',
    name_kn: 'ರಮೇಶ್ ಕುಮಾರ್ (ರೈತರು)',
    phone: '+91 7483254968',
    role: 'USER',
    language: 'kn',
    photoUrl: 'https://images.unsplash.com/photo-1544005313-94ddf0286df2?w=150',
    bio: 'Organic Arecanut & Coconut farmer in Central Muttagundi',
    bio_kn: 'ಮುತ್ತಾಗೊಂದಿ ಗ್ರಾಮದ ಸಾವಯವ ಅಡಿಕೆ & ತೆಂಗು ಬೆಳೆಗಾರರು',
    account_status: 'ACTIVE',
    created_at: new Date().toISOString(),
    last_login: new Date().toISOString(),
    is_phone_verified: true,
    community_category: 'FARMER',
    allow_find_me: true,
    privacy_find: 'EVERYONE',
    privacy_message: 'EVERYONE'
  },
  {
    uid: 'usr_manju_sports',
    name: 'Manjunatha M',
    name_kn: 'ಮಂಜುನಾಥ ಎಂ (ಕ್ರೀಡಾಪಟು)',
    phone: '+91 7483254968',
    role: 'SPORTS_ORGANIZER',
    language: 'kn',
    photoUrl: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=150',
    bio: 'Village Kabaddi & Cricket team captain, Hosadurga Taluk runner-up',
    bio_kn: 'ಮುತ್ತಾಗೊಂದಿ ಕಬಡ್ಡಿ & ಕ್ರಿಕೆಟ್ ತಂಡದ ನಾಯಕರು',
    account_status: 'ACTIVE',
    created_at: new Date().toISOString(),
    last_login: new Date().toISOString(),
    is_phone_verified: true,
    community_category: 'SPORTS',
    allow_find_me: true,
    privacy_find: 'EVERYONE',
    privacy_message: 'EVERYONE'
  },
  {
    uid: 'usr_sowmya_teacher',
    name: 'Sowmya Devi',
    name_kn: 'ಸೌಮ್ಯ ದೇವಿ (ಶಿಕ್ಷಕರು)',
    phone: '+91 7483254968',
    role: 'USER',
    language: 'kn',
    photoUrl: 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?w=150',
    bio: 'Primary School Teacher, Govt Lower Primary School Muttagundi',
    bio_kn: 'ಸರ್ಕಾರಿ ಕಿರಿಯ ಪ್ರಾಥಮಿಕ ಶಾಲೆ ಶಿಕ್ಷಕಿ, ಮುತ್ತಾಗೊಂದಿ',
    account_status: 'ACTIVE',
    created_at: new Date().toISOString(),
    last_login: new Date().toISOString(),
    is_phone_verified: true,
    community_category: 'TEACHER',
    allow_find_me: true,
    privacy_find: 'EVERYONE',
    privacy_message: 'EVERYONE'
  },
  {
    uid: 'usr_basavaraj_resident',
    name: 'Basavaraju K',
    name_kn: 'ಬಸವರಾಜು ಕೆ (ಗ್ರಾಮಸ್ಥರು)',
    phone: '+91 7483254968',
    role: 'USER',
    language: 'kn',
    photoUrl: 'https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?w=150',
    bio: 'Temple seva volunteer & community social coordinator',
    bio_kn: 'ದೇವಸ್ಥಾನ ಸೇವಾ ಸಮಿತಿ ಸದಸ್ಯರು & ಸಮಾಜ ಸೇವಕರು',
    account_status: 'ACTIVE',
    created_at: new Date().toISOString(),
    last_login: new Date().toISOString(),
    is_phone_verified: true,
    community_category: 'RESIDENT',
    allow_find_me: true,
    privacy_find: 'EVERYONE',
    privacy_message: 'EVERYONE'
  }
];

// Clean Real Statistics for Muttagundi, Hosadurga Taluk, Chitradurga
export const SEED_VILLAGE_STATS: VillageStats = {
  id: 'stats_main',
  population: 3450,
  households: 820,
  area_sqkm: 16.2,
  literacy_rate: 82.4,
  schools: 2,
  temples: 3,
  hospitals: 1,
  agricultural_land_acres: 2150,
  main_crops_en: 'Ragi, Groundnut, Maize, Coconut, Arecanut',
  main_crops_kn: 'ರಾಗಿ, ಕಡಲೆಕಾಯಿ, ಮೆಕ್ಕೆಜೋಳ, ತೆಂಗು, ಅಡಿಕೆ',
  active_members: 1,
  source: 'Muttagundi Grama Panchayat Official Census',
  source_url: 'https://panchamitra.karnataka.gov.in',
  last_verified: new Date().toISOString().split('T')[0],
  verified_by: 'Muttagundi Administration',
  is_demo: false
};

// All collections start completely empty and clean so real data can be added from scratch
export const SEED_EMERGENCY_ALERT: EmergencyAlert | null = null;
export const SEED_NEWS: NewsItem[] = [
  {
    id: 'news_muttagundi_1',
    title_en: 'Muttagundi Grama Sabha & Village Development Meeting Scheduled',
    title_kn: 'ಮುತ್ತಾಗೊಂದಿ ಗ್ರಾಮ ಸಭೆ ಮತ್ತು ಗ್ರಾಮ ಅಭಿವೃದ್ಧಿ ಸಭೆ ನಿಗದಿಯಾಗಿದೆ',
    content_en: 'The official Muttagundi Grama Sabha meeting will be held at the Village Community Hall on Sunday at 10:00 AM. All residents, farmers, and youth are requested to participate to discuss road repairs, drinking water distribution, and agricultural schemes.',
    content_kn: 'ಮುತ್ತಾಗೊಂದಿ ಗ್ರಾಮದ ಅಧಿಕೃತ ಗ್ರಾಮ ಸಭೆಯು ಮುಂಬರುವ ಭಾನುವಾರ ಬೆಳಿಗ್ಗೆ 10:00 ಗಂಟೆಗೆ ಗ್ರಾಮದ ಸಮುದಾಯ ಭವನದಲ್ಲಿ ನಡೆಯಲಿದೆ. ರಸ್ತೆ ದುರಸ್ತಿ, ಕುಡಿಯುವ ನೀರಿನ ಸೌಲಭ್ಯ, ಮತ್ತು ಕೃಷಿ ಯೋಜನೆಗಳ ಕುರಿತು ಚರ್ಚಿಸಲು ಎಲ್ಲಾ ಗ್ರಾಮಸ್ಥರು, ರೈತ ಬಾಂಧವರು ಹಾಗೂ ಯುವಕರು ಭಾಗವಹಿಸಲು ಕೋರಲಾಗಿದೆ.',
    category: 'COMMUNITY',
    media_url: 'https://images.unsplash.com/photo-1541872703-74c5e44368f9?w=800&auto=format&fit=crop',
    media_type: 'IMAGE',
    location: 'Muttagundi Community Hall, Hosadurga Taluk',
    author_id: 'admin_vvini4803',
    author_name: 'Muttagundi Administration',
    author_role: 'SUPER_ADMIN',
    verification_status: 'VERIFIED',
    auto_verified: true,
    verified_by: 'admin_vvini4803',
    verified_by_name: 'ವಿನಯ್ (ಮುಖ್ಯ ಸೂಪರ್ ಅಡ್ಮಿನ್)',
    verified_at: new Date().toISOString(),
    urgent: false,
    pinned: true,
    likes_count: 14,
    liked_by: [],
    comments_count: 2,
    reports_count: 0,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
    active_until: new Date(Date.now() + 7 * 24 * 60 * 60 * 1000).toISOString(),
    is_demo: false
  },
  {
    id: 'news_muttagundi_2',
    title_en: 'Monsoon Crop Advisory & Soil Testing Camp at Raitha Samparka Kendra',
    title_kn: 'ರೈತ ಸಂಪರ್ಕ ಕೇಂದ್ರದಲ್ಲಿ ಮುಂಗಾರು ಬೆಳೆ ಸಲಹೆ ಮತ್ತು ಮಣ್ಣು ಪರೀಕ್ಷೆ ಶಿಬಿರ',
    content_en: 'Department of Agriculture is organizing a free soil testing camp and providing subsidized quality seeds (Ragi, Groundnut, Maize) for Muttagundi farmers this week.',
    content_kn: 'ಕೃಷಿ ಇಲಾಖೆಯ ವತಿಯಿಂದ ಮುತ್ತಾಗೊಂದಿ ಗ್ರಾಮದ ರೈತರಿಗೆ ಉಚಿತ ಮಣ್ಣು ಪರೀಕ್ಷೆ ಶಿಬಿರ ಹಾಗೂ ರಿಯಾಯಿತಿ ದರದಲ್ಲಿ ಗುಣಮಟ್ಟದ ರಾಗಿ, ಕಡಲೆಕಾಯಿ ಹಾಗೂ ಮೆಕ್ಕೆಜೋಳ ಬೀಜ ವಿತರಣೆ ಈ ವಾರ ನಡೆಯಲಿದೆ.',
    category: 'AGRICULTURE',
    media_url: 'https://images.unsplash.com/photo-1500937386664-56d1dfef3854?w=800&auto=format&fit=crop',
    media_type: 'IMAGE',
    location: 'Raitha Samparka Kendra, Muttagundi',
    author_id: 'admin_vvini4803',
    author_name: 'Muttagundi Raitha Kendra',
    author_role: 'SUPER_ADMIN',
    verification_status: 'VERIFIED',
    auto_verified: true,
    verified_by: 'admin_vvini4803',
    verified_by_name: 'ವಿನಯ್ (ಮುಖ್ಯ ಸೂಪರ್ ಅಡ್ಮಿನ್)',
    verified_at: new Date().toISOString(),
    urgent: false,
    pinned: false,
    likes_count: 19,
    liked_by: [],
    comments_count: 3,
    reports_count: 0,
    created_at: new Date(Date.now() - 3600000 * 10).toISOString(),
    updated_at: new Date(Date.now() - 3600000 * 10).toISOString(),
    active_until: new Date(Date.now() + 7 * 24 * 60 * 60 * 1000).toISOString(),
    is_demo: false
  },
  {
    id: 'news_muttagundi_3',
    title_en: 'Drinking Water Pipeline & RO Plant Maintenance Completed',
    title_kn: 'ಶುದ್ಧ ಕುಡಿಯುವ ನೀರಿನ ಪೈಪ್‌ಲೈನ್ ಮತ್ತು ಆರ್‌ಒ ಪ್ಲಾಂಟ್ ನಿರ್ವಹಣೆ ಪೂರ್ಣಗೊಂಡಿದೆ',
    content_en: 'Regular maintenance and filter replacement of the Muttagundi clean drinking water unit have been successfully completed. 24/7 drinking water supply is fully restored.',
    content_kn: 'ಮುತ್ತಾಗೊಂದಿ ಗ್ರಾಮದ ಶುದ್ಧ ಕುಡಿಯುವ ನೀರಿನ ಘಟಕದ ಫಿಲ್ಟರ್ ಬದಲಾವಣೆ ಹಾಗೂ ಪೈಪ್‌ಲೈನ್ ನಿರ್ವಹಣಾ ಕಾರ್ಯ ಯಶಸ್ವಿಯಾಗಿ ಪೂರ್ಣಗೊಂಡಿದೆ. ಕುಡಿಯುವ ನೀರಿನ ಸರಬರಾಜು ಸಹಜ ಸ್ಥಿತಿಗೆ ಮರಳಿದೆ.',
    category: 'WATER',
    media_url: 'https://images.unsplash.com/photo-1574482620811-1aa16ffe3c82?w=800&auto=format&fit=crop',
    media_type: 'IMAGE',
    location: 'Water Tank Ward, Muttagundi',
    author_id: 'admin_vvini4803',
    author_name: 'Muttagundi Water Works',
    author_role: 'SUPER_ADMIN',
    verification_status: 'VERIFIED',
    auto_verified: true,
    verified_by: 'admin_vvini4803',
    verified_by_name: 'ವಿನಯ್ (ಮುಖ್ಯ ಸೂಪರ್ ಅಡ್ಮಿನ್)',
    verified_at: new Date().toISOString(),
    urgent: false,
    pinned: false,
    likes_count: 24,
    liked_by: [],
    comments_count: 1,
    reports_count: 0,
    created_at: new Date(Date.now() - 3600000 * 20).toISOString(),
    updated_at: new Date(Date.now() - 3600000 * 20).toISOString(),
    active_until: new Date(Date.now() + 7 * 24 * 60 * 60 * 1000).toISOString(),
    is_demo: false
  }
];
export const SEED_EVENTS: EventItem[] = [];
export const SEED_TOURNAMENTS: Tournament[] = [];
export const SEED_CROPS: CropItem[] = [];
export const SEED_TEMPLES: TempleItem[] = [];
export const SEED_HISTORY: HistoryItem[] = [];
export const SEED_STORIES: StoryItem[] = [];
export const SEED_ACHIEVEMENTS: AchievementItem[] = [];
export const SEED_GALLERY: GalleryItem[] = [];
export const SEED_SOCIAL_LINKS: SocialLink[] = [];
export const SEED_CONVERSATIONS: Conversation[] = [];
export const SEED_MESSAGES: ChatMessage[] = [];

// ==========================================
// 🏛️ SEED DATA: MTG COMMITTEE & FINANCIALS
// ==========================================

export const SEED_COMMITTEE_MEMBERS: CommitteeMember[] = [
  {
    id: 'mem_1',
    user_id: 'admin_vvini4803',
    name: 'Vinay Kumar',
    name_kn: 'ವಿನಯ್ ಕುಮಾರ್',
    phone: '+91 7483254968',
    address: 'Main Street, Central Muttagundi',
    joining_date: '2023-01-15',
    role: 'PRESIDENT',
    role_kn: 'ಅಧ್ಯಕ್ಷರು',
    status: 'ACTIVE',
    photo_url: 'https://api.dicebear.com/7.x/bottts/svg?seed=vvini4803',
    total_contributed: 12000,
    active_loans_count: 0,
    outstanding_loan_balance: 0,
    created_at: '2023-01-15T10:00:00.000Z'
  },
  {
    id: 'mem_2',
    name: 'Ramesh Gowda',
    name_kn: 'ರಮೇಶ್ ಗೌಡ',
    phone: '+91 9845123401',
    address: 'Near Old Bus Stand, Muttagundi',
    joining_date: '2023-01-15',
    role: 'VICE_PRESIDENT',
    role_kn: 'ಉಪಾಧ್ಯಕ್ಷರು',
    status: 'ACTIVE',
    photo_url: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=150&auto=format&fit=crop',
    total_contributed: 12000,
    active_loans_count: 1,
    outstanding_loan_balance: 15600,
    created_at: '2023-01-15T10:00:00.000Z'
  },
  {
    id: 'mem_3',
    name: 'Basavaraj M',
    name_kn: 'ಬಸವರಾಜ್ ಎಂ',
    phone: '+91 9845123402',
    address: 'School Road, Muttagundi',
    joining_date: '2023-01-20',
    role: 'SECRETARY',
    role_kn: 'ಕಾರ್ಯದರ್ಶಿ',
    status: 'ACTIVE',
    photo_url: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=150&auto=format&fit=crop',
    total_contributed: 12000,
    active_loans_count: 0,
    outstanding_loan_balance: 0,
    created_at: '2023-01-20T10:00:00.000Z'
  },
  {
    id: 'mem_4',
    name: 'Suresh Patil',
    name_kn: 'ಸುರೇಶ್ ಪಾಟೀಲ್',
    phone: '+91 9845123403',
    address: 'Car Street, Muttagundi',
    joining_date: '2023-01-20',
    role: 'TREASURER',
    role_kn: 'ಖಜಾಂಚಿ',
    status: 'ACTIVE',
    photo_url: 'https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=150&auto=format&fit=crop',
    total_contributed: 12000,
    active_loans_count: 0,
    outstanding_loan_balance: 0,
    created_at: '2023-01-20T10:00:00.000Z'
  },
  {
    id: 'mem_5',
    name: 'Shivanna K',
    name_kn: 'ಶಿವಣ್ಣ ಕೆ',
    phone: '+91 9845123404',
    address: 'Temple Ward, Muttagundi',
    joining_date: '2023-02-01',
    role: 'DIRECTOR',
    role_kn: 'ನಿರ್ದೇಶಕರು',
    status: 'ACTIVE',
    photo_url: 'https://images.unsplash.com/photo-1519085360753-af0119f7cbe7?w=150&auto=format&fit=crop',
    total_contributed: 11000,
    active_loans_count: 1,
    outstanding_loan_balance: 20800,
    created_at: '2023-02-01T10:00:00.000Z'
  },
  {
    id: 'mem_6',
    name: 'Manjula Devi',
    name_kn: 'ಮಂಜುಳಾ ದೇವಿ',
    phone: '+91 9845123405',
    address: 'Anganwadi Lane, Muttagundi',
    joining_date: '2023-02-10',
    role: 'DIRECTOR',
    role_kn: 'ನಿರ್ದೇಶಕರು',
    status: 'ACTIVE',
    photo_url: 'https://images.unsplash.com/photo-1544005313-94ddf0286df2?w=150&auto=format&fit=crop',
    total_contributed: 12000,
    active_loans_count: 0,
    outstanding_loan_balance: 0,
    created_at: '2023-02-10T10:00:00.000Z'
  },
  {
    id: 'mem_7',
    name: 'Channappa H',
    name_kn: 'ಚನ್ನಪ್ಪ ಹೆಚ್',
    phone: '+91 9845123406',
    address: 'Water Tank Ward, Muttagundi',
    joining_date: '2023-03-01',
    role: 'MEMBER',
    role_kn: 'ಸದಸ್ಯರು',
    status: 'ACTIVE',
    photo_url: 'https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?w=150&auto=format&fit=crop',
    total_contributed: 10000,
    active_loans_count: 1,
    outstanding_loan_balance: 10400,
    created_at: '2023-03-01T10:00:00.000Z'
  },
  {
    id: 'mem_8',
    name: 'Sunitha B',
    name_kn: 'ಸುನಿತಾ ಬಿ',
    phone: '+91 9845123407',
    address: 'Hospital Cross, Muttagundi',
    joining_date: '2023-03-15',
    role: 'MEMBER',
    role_kn: 'ಸದಸ್ಯರು',
    status: 'ACTIVE',
    photo_url: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=150&auto=format&fit=crop',
    total_contributed: 12000,
    active_loans_count: 0,
    outstanding_loan_balance: 0,
    created_at: '2023-03-15T10:00:00.000Z'
  },
  {
    id: 'mem_9',
    name: 'Malleshappa S',
    name_kn: 'ಮಲ್ಲೇಶಪ್ಪ ಎಸ್',
    phone: '+91 9845123408',
    address: 'Farmer Colony, Muttagundi',
    joining_date: '2023-04-01',
    role: 'MEMBER',
    role_kn: 'ಸದಸ್ಯರು',
    status: 'ACTIVE',
    photo_url: 'https://images.unsplash.com/photo-1522075469751-3a6694fb2f61?w=150&auto=format&fit=crop',
    total_contributed: 9000,
    active_loans_count: 0,
    outstanding_loan_balance: 0,
    created_at: '2023-04-01T10:00:00.000Z'
  },
  {
    id: 'mem_10',
    name: 'Girish N',
    name_kn: 'ಗಿರೀಶ್ ಎನ್',
    phone: '+91 9845123409',
    address: 'East Gate, Muttagundi',
    joining_date: '2023-04-15',
    role: 'MEMBER',
    role_kn: 'ಸದಸ್ಯರು',
    status: 'ACTIVE',
    photo_url: 'https://images.unsplash.com/photo-1492562080023-ab3db95bfbce?w=150&auto=format&fit=crop',
    total_contributed: 12000,
    active_loans_count: 0,
    outstanding_loan_balance: 0,
    created_at: '2023-04-15T10:00:00.000Z'
  }
];

export const SEED_COMMITTEE_CONTRIBUTIONS: CommitteeContribution[] = [
  // Current Month: September 2026 (7 Paid, 3 Pending)
  {
    id: 'cnt_2026_09_01',
    member_id: 'mem_1',
    member_name: 'Vinay Kumar',
    month: '2026-09',
    month_label_en: 'September 2026',
    month_label_kn: 'ಸೆಪ್ಟೆಂಬರ್ ೨೦೨೬',
    expected_amount: 1000,
    amount_paid: 1000,
    status: 'PAID',
    payment_date: '2026-09-05',
    reference_id: 'UPI-MTG-9001',
    notes: 'Online UPI transfer to Committee Fund',
    collected_by: 'Suresh Patil (Treasurer)',
    created_at: '2026-09-05T09:30:00.000Z'
  },
  {
    id: 'cnt_2026_09_02',
    member_id: 'mem_2',
    member_name: 'Ramesh Gowda',
    month: '2026-09',
    month_label_en: 'September 2026',
    month_label_kn: 'ಸೆಪ್ಟೆಂಬರ್ ೨೦೨೬',
    expected_amount: 1000,
    amount_paid: 0,
    status: 'PENDING',
    notes: 'Pending collection by 28th Sep',
    created_at: '2026-09-01T08:00:00.000Z'
  },
  {
    id: 'cnt_2026_09_03',
    member_id: 'mem_3',
    member_name: 'Basavaraj M',
    month: '2026-09',
    month_label_en: 'September 2026',
    month_label_kn: 'ಸೆಪ್ಟೆಂಬರ್ ೨೦೨೬',
    expected_amount: 1000,
    amount_paid: 1000,
    status: 'PAID',
    payment_date: '2026-09-06',
    reference_id: 'CASH-REC-102',
    notes: 'Cash payment handed to Treasurer',
    collected_by: 'Suresh Patil (Treasurer)',
    created_at: '2026-09-06T11:00:00.000Z'
  },
  {
    id: 'cnt_2026_09_04',
    member_id: 'mem_4',
    member_name: 'Suresh Patil',
    month: '2026-09',
    month_label_en: 'September 2026',
    month_label_kn: 'ಸೆಪ್ಟೆಂಬರ್ ೨೦೨೬',
    expected_amount: 1000,
    amount_paid: 1000,
    status: 'PAID',
    payment_date: '2026-09-02',
    reference_id: 'BANK-TRF-404',
    notes: 'Direct Bank deposit',
    collected_by: 'Self (Treasurer)',
    created_at: '2026-09-02T10:15:00.000Z'
  },
  {
    id: 'cnt_2026_09_05',
    member_id: 'mem_5',
    member_name: 'Shivanna K',
    month: '2026-09',
    month_label_en: 'September 2026',
    month_label_kn: 'ಸೆಪ್ಟೆಂಬರ್ ೨೦೨೬',
    expected_amount: 1000,
    amount_paid: 1000,
    status: 'PAID',
    payment_date: '2026-09-08',
    reference_id: 'UPI-MTG-9022',
    notes: 'PhonePe payment',
    collected_by: 'Suresh Patil (Treasurer)',
    created_at: '2026-09-08T15:20:00.000Z'
  },
  {
    id: 'cnt_2026_09_06',
    member_id: 'mem_6',
    member_name: 'Manjula Devi',
    month: '2026-09',
    month_label_en: 'September 2026',
    month_label_kn: 'ಸೆಪ್ಟೆಂಬರ್ ೨೦೨೬',
    expected_amount: 1000,
    amount_paid: 1000,
    status: 'PAID',
    payment_date: '2026-09-04',
    reference_id: 'CASH-REC-105',
    notes: 'Paid at Monthly Meeting',
    collected_by: 'Suresh Patil (Treasurer)',
    created_at: '2026-09-04T12:00:00.000Z'
  },
  {
    id: 'cnt_2026_09_07',
    member_id: 'mem_7',
    member_name: 'Channappa H',
    month: '2026-09',
    month_label_en: 'September 2026',
    month_label_kn: 'ಸೆಪ್ಟೆಂಬರ್ ೨೦೨೬',
    expected_amount: 1000,
    amount_paid: 0,
    status: 'PENDING',
    notes: 'Awaiting crop sale proceeds',
    created_at: '2026-09-01T08:00:00.000Z'
  },
  {
    id: 'cnt_2026_09_08',
    member_id: 'mem_8',
    member_name: 'Sunitha B',
    month: '2026-09',
    month_label_en: 'September 2026',
    month_label_kn: 'ಸೆಪ್ಟೆಂಬರ್ ೨೦೨೬',
    expected_amount: 1000,
    amount_paid: 1000,
    status: 'PAID',
    payment_date: '2026-09-03',
    reference_id: 'UPI-MTG-9031',
    notes: 'Google Pay to Committee account',
    collected_by: 'Suresh Patil (Treasurer)',
    created_at: '2026-09-03T14:10:00.000Z'
  },
  {
    id: 'cnt_2026_09_09',
    member_id: 'mem_9',
    member_name: 'Malleshappa S',
    month: '2026-09',
    month_label_en: 'September 2026',
    month_label_kn: 'ಸೆಪ್ಟೆಂಬರ್ ೨೦೨೬',
    expected_amount: 1000,
    amount_paid: 0,
    status: 'PENDING',
    notes: 'Reminder sent via SMS',
    created_at: '2026-09-01T08:00:00.000Z'
  },
  {
    id: 'cnt_2026_09_10',
    member_id: 'mem_10',
    member_name: 'Girish N',
    month: '2026-09',
    month_label_en: 'September 2026',
    month_label_kn: 'ಸೆಪ್ಟೆಂಬರ್ ೨೦೨೬',
    expected_amount: 1000,
    amount_paid: 1000,
    status: 'PAID',
    payment_date: '2026-09-07',
    reference_id: 'CASH-REC-108',
    notes: 'Paid at meeting',
    collected_by: 'Suresh Patil (Treasurer)',
    created_at: '2026-09-07T16:00:00.000Z'
  }
];

export const SEED_COMMITTEE_LOANS: CommitteeLoan[] = [
  {
    id: 'loan_1',
    loan_number: 'LN-2026-001',
    member_id: 'mem_2',
    member_name: 'Ramesh Gowda',
    principal_amount: 30000,
    loan_date: '2026-04-10',
    interest_rate_percent: 2, // 2% per month
    interest_type: 'SIMPLE_MONTHLY',
    tenure_months: 6,
    monthly_due_amount: 5600,
    due_date: '2026-10-10',
    total_interest_payable: 3600,
    total_amount_payable: 33600,
    amount_paid: 18000, // 15,000 principal + 3,000 interest
    remaining_principal: 15000,
    remaining_interest: 600,
    status: 'PARTIALLY_PAID',
    purpose: 'Drip irrigation pipes & sprinkler setup for 3 acres',
    repayments: [
      {
        id: 'rep_1_1',
        loan_id: 'loan_1',
        member_id: 'mem_2',
        member_name: 'Ramesh Gowda',
        amount: 6000,
        principal_portion: 5000,
        interest_portion: 1000,
        payment_date: '2026-05-10',
        reference_id: 'REP-001',
        received_by: 'Suresh Patil',
        notes: 'Month 1 installment',
        created_at: '2026-05-10T11:00:00.000Z'
      },
      {
        id: 'rep_1_2',
        loan_id: 'loan_1',
        member_id: 'mem_2',
        member_name: 'Ramesh Gowda',
        amount: 6000,
        principal_portion: 5000,
        interest_portion: 1000,
        payment_date: '2026-06-10',
        reference_id: 'REP-002',
        received_by: 'Suresh Patil',
        notes: 'Month 2 installment',
        created_at: '2026-06-10T11:00:00.000Z'
      },
      {
        id: 'rep_1_3',
        loan_id: 'loan_1',
        member_id: 'mem_2',
        member_name: 'Ramesh Gowda',
        amount: 6000,
        principal_portion: 5000,
        interest_portion: 1000,
        payment_date: '2026-07-10',
        reference_id: 'REP-003',
        received_by: 'Suresh Patil',
        notes: 'Month 3 installment',
        created_at: '2026-07-10T11:00:00.000Z'
      }
    ],
    created_at: '2026-04-10T10:00:00.000Z'
  },
  {
    id: 'loan_2',
    loan_number: 'LN-2026-002',
    member_id: 'mem_5',
    member_name: 'Shivanna K',
    principal_amount: 25000,
    loan_date: '2026-06-15',
    interest_rate_percent: 2,
    interest_type: 'SIMPLE_MONTHLY',
    tenure_months: 5,
    monthly_due_amount: 5500,
    due_date: '2026-11-15',
    total_interest_payable: 2500,
    total_amount_payable: 27500,
    amount_paid: 6700, // 5,000 principal + 1,700 interest
    remaining_principal: 20000,
    remaining_interest: 800,
    status: 'ACTIVE',
    purpose: 'HF dairy cow purchase & fodder storage',
    repayments: [
      {
        id: 'rep_2_1',
        loan_id: 'loan_2',
        member_id: 'mem_5',
        member_name: 'Shivanna K',
        amount: 6700,
        principal_portion: 5000,
        interest_portion: 1700,
        payment_date: '2026-07-15',
        reference_id: 'REP-004',
        received_by: 'Suresh Patil',
        notes: 'Initial installment',
        created_at: '2026-07-15T12:00:00.000Z'
      }
    ],
    created_at: '2026-06-15T10:00:00.000Z'
  },
  {
    id: 'loan_3',
    loan_number: 'LN-2026-003',
    member_id: 'mem_7',
    member_name: 'Channappa H',
    principal_amount: 15000,
    loan_date: '2026-07-01',
    interest_rate_percent: 2,
    interest_type: 'SIMPLE_MONTHLY',
    tenure_months: 3,
    monthly_due_amount: 5300,
    due_date: '2026-10-01',
    total_interest_payable: 900,
    total_amount_payable: 15900,
    amount_paid: 5500, // 5,000 principal + 500 interest
    remaining_principal: 10000,
    remaining_interest: 400,
    status: 'ACTIVE',
    purpose: 'Ragi seeds & natural compost fertilizer purchase',
    repayments: [
      {
        id: 'rep_3_1',
        loan_id: 'loan_3',
        member_id: 'mem_7',
        member_name: 'Channappa H',
        amount: 5500,
        principal_portion: 5000,
        interest_portion: 500,
        payment_date: '2026-08-01',
        reference_id: 'REP-005',
        received_by: 'Suresh Patil',
        notes: 'First installment',
        created_at: '2026-08-01T10:00:00.000Z'
      }
    ],
    created_at: '2026-07-01T10:00:00.000Z'
  },
  {
    id: 'loan_4',
    loan_number: 'LN-2026-004',
    member_id: 'mem_10',
    member_name: 'Girish N',
    principal_amount: 20000,
    loan_date: '2026-02-01',
    interest_rate_percent: 2,
    interest_type: 'SIMPLE_MONTHLY',
    tenure_months: 4,
    monthly_due_amount: 5400,
    due_date: '2026-06-01',
    total_interest_payable: 1600,
    total_amount_payable: 21600,
    amount_paid: 21600,
    remaining_principal: 0,
    remaining_interest: 0,
    status: 'FULLY_PAID',
    purpose: 'Submersible borewell pump replacement',
    repayments: [
      {
        id: 'rep_4_1',
        loan_id: 'loan_4',
        member_id: 'mem_10',
        member_name: 'Girish N',
        amount: 21600,
        principal_portion: 20000,
        interest_portion: 1600,
        payment_date: '2026-05-28',
        reference_id: 'REP-006-FULL',
        received_by: 'Suresh Patil',
        notes: 'Full early loan closure with interest',
        created_at: '2026-05-28T14:00:00.000Z'
      }
    ],
    created_at: '2026-02-01T10:00:00.000Z'
  }
];

export const SEED_COMMITTEE_EXPENSES: CommitteeExpense[] = [
  {
    id: 'exp_1',
    category: 'TEMPLE',
    category_kn: 'ದೇವಸ್ಥಾನ ಅಭಿವೃದ್ಧಿ',
    amount: 4500,
    date: '2026-08-15',
    description: 'Sri Ranganatha Swamy Temple decorative lighting for Festival',
    paid_by: 'Suresh Patil (Treasurer)',
    receipt_url: 'https://images.unsplash.com/photo-1554224155-8d04cb21cd6c?w=600&auto=format&fit=crop',
    created_by: 'admin_vvini4803',
    created_at: '2026-08-15T16:00:00.000Z'
  },
  {
    id: 'exp_2',
    category: 'ELECTRICITY',
    category_kn: 'ವಿದ್ಯುತ್ & ಬೀದಿದೀಪ',
    amount: 3200,
    date: '2026-08-28',
    description: 'Main Street & Temple road LED streetlight fixture repairs',
    paid_by: 'Basavaraj M (Secretary)',
    receipt_url: 'https://images.unsplash.com/photo-1554224154-26032ffc0d07?w=600&auto=format&fit=crop',
    created_by: 'admin_vvini4803',
    created_at: '2026-08-28T14:30:00.000Z'
  },
  {
    id: 'exp_3',
    category: 'SPORTS',
    category_kn: 'ಕ್ರೀಡಾ ಪ್ರೋತ್ಸಾಹ',
    amount: 5000,
    date: '2026-09-02',
    description: 'Muttagundi Youth Cricket & Kabaddi tournament shields and balls',
    paid_by: 'Vinay Kumar (President)',
    receipt_url: 'https://images.unsplash.com/photo-1554224155-6726b3ff858f?w=600&auto=format&fit=crop',
    created_by: 'admin_vvini4803',
    created_at: '2026-09-02T11:00:00.000Z'
  },
  {
    id: 'exp_4',
    category: 'ADMINISTRATION',
    category_kn: 'ಆಡಳಿತ & ಸಭೆ ಖರ್ಚು',
    amount: 1800,
    date: '2026-09-10',
    description: 'Committee ledger books, printing registers & Grama Sabha tea',
    paid_by: 'Suresh Patil (Treasurer)',
    receipt_url: 'https://images.unsplash.com/photo-1554224155-1696413565d3?w=600&auto=format&fit=crop',
    created_by: 'admin_vvini4803',
    created_at: '2026-09-10T17:00:00.000Z'
  }
];

export const SEED_COMMITTEE_TRANSACTIONS: CommitteeTransaction[] = [
  {
    id: 'txn_101',
    date: '2026-09-05',
    time: '09:30 AM',
    member_id: 'mem_1',
    member_name: 'Vinay Kumar',
    type: 'FUND_CONTRIBUTION',
    type_kn: 'ಮಾಸಿಕ ನಿಧಿ ಪಾವತಿ',
    amount: 1000,
    direction: 'IN',
    description: 'Monthly fund contribution for September 2026',
    reference_id: 'UPI-MTG-9001',
    created_by: 'Suresh Patil',
    status: 'COMPLETED',
    created_at: '2026-09-05T09:30:00.000Z'
  },
  {
    id: 'txn_102',
    date: '2026-09-06',
    time: '11:00 AM',
    member_id: 'mem_3',
    member_name: 'Basavaraj M',
    type: 'FUND_CONTRIBUTION',
    type_kn: 'ಮಾಸಿಕ ನಿಧಿ ಪಾವತಿ',
    amount: 1000,
    direction: 'IN',
    description: 'Monthly fund contribution for September 2026 (Cash)',
    reference_id: 'CASH-REC-102',
    created_by: 'Suresh Patil',
    status: 'COMPLETED',
    created_at: '2026-09-06T11:00:00.000Z'
  },
  {
    id: 'txn_103',
    date: '2026-09-02',
    time: '11:00 AM',
    member_id: 'mem_1',
    member_name: 'Vinay Kumar',
    type: 'EXPENSE',
    type_kn: 'ಸಮಿತಿ ವೆಚ್ಚ',
    amount: 5000,
    direction: 'OUT',
    description: 'Youth sports tournament shields and balls',
    reference_id: 'EXP-SPORTS-09',
    created_by: 'admin_vvini4803',
    status: 'COMPLETED',
    created_at: '2026-09-02T11:00:00.000Z'
  },
  {
    id: 'txn_104',
    date: '2026-08-01',
    time: '10:00 AM',
    member_id: 'mem_7',
    member_name: 'Channappa H',
    type: 'LOAN_REPAYMENT',
    type_kn: 'ಸಾಲ ಮರುಪಾವತಿ',
    amount: 5000,
    direction: 'IN',
    description: 'Principal repayment on Loan #LN-2026-003',
    reference_id: 'REP-005',
    created_by: 'Suresh Patil',
    status: 'COMPLETED',
    created_at: '2026-08-01T10:00:00.000Z'
  },
  {
    id: 'txn_105',
    date: '2026-08-01',
    time: '10:00 AM',
    member_id: 'mem_7',
    member_name: 'Channappa H',
    type: 'INTEREST_PAYMENT',
    type_kn: 'ಬಡ್ಡಿ ಸಂಗ್ರಹ',
    amount: 500,
    direction: 'IN',
    description: 'Interest on Loan #LN-2026-003 for July',
    reference_id: 'REP-005-INT',
    created_by: 'Suresh Patil',
    status: 'COMPLETED',
    created_at: '2026-08-01T10:00:00.000Z'
  },
  {
    id: 'txn_106',
    date: '2026-09-10',
    time: '05:00 PM',
    type: 'EXPENSE',
    type_kn: 'ಸಮಿತಿ ವೆಚ್ಚ',
    amount: 1800,
    direction: 'OUT',
    description: 'Stationery registers & Grama Sabha meeting tea',
    reference_id: 'EXP-ADM-010',
    created_by: 'Suresh Patil',
    status: 'COMPLETED',
    created_at: '2026-09-10T17:00:00.000Z'
  }
];

export const SEED_COMMITTEE_AUDIT_LOGS: CommitteeAuditLog[] = [
  {
    id: 'audit_1',
    action: 'INIT_COMMITTEE_SYSTEM',
    action_kn: 'ಸಮಿತಿ ವ್ಯವಸ್ಥೆ ಪ್ರಾರಂಭಿಸಲಾಗಿದೆ',
    actor_id: 'admin_vvini4803',
    actor_name: 'Vinay Kumar (Super Admin)',
    target_id: 'committee_config',
    target_type: 'SYSTEM',
    details: 'Muttagundi Village Committee financial module initialized with 10 members and verified ledger.',
    timestamp: '2026-09-01T08:00:00.000Z'
  },
  {
    id: 'audit_2',
    action: 'RECORD_CONTRIBUTION',
    action_kn: 'ಮಾಸಿಕ ನಿಧಿ ದಾಖಲಿಸಲಾಗಿದೆ',
    actor_id: 'mem_4',
    actor_name: 'Suresh Patil (Treasurer)',
    target_id: 'cnt_2026_09_01',
    target_type: 'CONTRIBUTION',
    details: 'Recorded ₹1,000 contribution from Vinay Kumar via UPI for September 2026.',
    timestamp: '2026-09-05T09:30:00.000Z'
  },
  {
    id: 'audit_3',
    action: 'CREATE_EXPENSE',
    action_kn: 'ಹೊಸ ವೆಚ್ಚ ದಾಖಲಿಸಲಾಗಿದೆ',
    actor_id: 'admin_vvini4803',
    actor_name: 'Vinay Kumar (President)',
    target_id: 'exp_3',
    target_type: 'EXPENSE',
    previous_value: '₹0',
    new_value: '₹5,000',
    details: 'Approved ₹5,000 youth sports tournament equipment sponsorship.',
    timestamp: '2026-09-02T11:00:00.000Z'
  }
];

